### PR TITLE
options for controling background color and using background instead of underline

### PR DESCRIPTION
**Pull request by szymonkaliski**
Choose running with: `ls | choose -c ECE8BE -b 345EF2 -s 18 -w 20 -u`

screen shot 2015-03-22 at 10 41 33

Choose running with: `ls | choose -c ECE8BE -b 345EF2 -s 18 -w 20`

screen shot 2015-03-22 at 10 41 42

Updated info:

```
$ choose -h
usage: choose
 -i           return index of selected element
 -v           show choose version
 -n [10]      set number of rows
 -w [50]      set width of choose window
 -f [Menlo]   set font used by choose
 -s [26]      set font size used by choose
 -c [0000FF]  highlight color for matched string
 -b [222222]  background color of selected element
 -u           disable underline and use background for matched string
```

### CODE REVIEW

**Comment by szymonkaliski** [comment]
Ideally I'd love to be able to set choose options to imitate xcode quick open window:

screen shot 2015-03-22 at 10 59 20

**Comment by sdegutis** [comment]
Sounds very cool! On my way to Mass though, will check this out in more depth later.

**Comment by sdegutis** [comment]
@szymonkaliski Can you edit your commit to not have all these whitespace changes? Once you do that I'll merge it.

**Comment by szymonkaliski** [comment]
Hey, it should be better with this commit: https://github.com/szymonkaliski/choose/commit/876b450a32cdff231696f76f91cc384897f97b7a ?

What about the swift re-write?

**Comment by sdegutis** [comment]
@szymonkaliski I've merged the Swift rewrote into a branch on this repo now. It has some bugs that I can't figure out, but I'm working on it. Starting with the command line parser, which I'm working on at https://github.com/sdegutis/Optitron and which I'll merge when it's working.

**Comment by szymonkaliski** [comment]
Could you list those bugs somewhere, maybe as issues? I think I'd be interested in helping out, I use FZF heavily for terminal, but GUI counterpart for macvim (and other scripts) would be great... :)

**Comment by sdegutis** [comment]
Sure.

**Pull request merged**
