### PR TITLE
Return query string in case of no match.

### PR DESCRIPTION
**Pull request by yoavg**
Implement #6 .

### CODE REVIEW

**Comment by sdegutis** [comment]
Hey nice job!

**Comment by sdegutis** [comment]
Can you make this be an option? I'm not sure everyone would want this behavior by default.

**Comment by sdegutis** [comment]
You can use `SDReturnsIndex` as an example of how to do it. It's mostly C at this point so don't worry about Objective-C syntax.

**Comment by yoavg** [comment]
I think I got it, seems to work (I pushed the change).

**Comment by sdegutis** [comment]
Closer! When there are no matching choices, shouldn't it `exit(1)` if `SDReturnStringOnMismatch` is false and `exit(0)` if `SDReturnStringOnMismatch` is true?

**Comment by yoavg** [comment]
done, but my commit log now has also another feature I implemented for my own usage -- optional specification of the menu items as an argument. If you prefer not to include it, I can remove it from the pull request (how?).

**Comment by sdegutis** [comment]
Use git to rebase it interactively to rearrange the two commits. Since the diffs aren't anywhere near each other, it shouldn't have any conflicts, it should be a clean rebase. Then put your fourth commit on another branch, move the PR's branch back to the third commit, and I'll merge it. Then merge your fourth commit back onto that branch and feel free to send another PR if it's ready ;)

**Comment by dme** [comment]
I'd love the -m functionality implemented here. @yoavg - any plan to re-jig the commits as requested? I could do it if you are no longer interested.

**Comment by yoavg** [comment]
sorry, couldn't find the time to do it properly. I'm using it locally and
it works well for me.

**Comment by dme** [comment]
I've submitted a new pull request with the merged commit for -m.

**Comment by sdegutis** [comment]
Thanks! It's merged now.

**Pull request closed without merging**
